events {}

http {
    server {
        listen 80;

        location /auth          { proxy_pass http://auth:8000; }
        location /cameras       { proxy_pass http://camera_registry:8011; }
        location /alerts        { proxy_pass http://alert_management:8000; }
        location /incidents     { proxy_pass http://incident_management:8000; }
        location /audit         { proxy_pass http://audit:8000; }
        location /notifications { proxy_pass http://notification:8000; }
        # location /reports     { proxy_pass http://reporting:8000; }
        location /ingestion     { proxy_pass http://ingestion:8020; }
        location /uc3 { proxy_pass http://host.docker.internal:8030; }
        
        location / { return 200 "Innovision gateway running"; }
    }
}
