events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;

        location /auth          { set $u http://auth:8000;                proxy_pass $u; }
        location /cameras       { set $u http://camera_registry:8011;     proxy_pass $u; }
        location /alerts        { set $u http://alert_management:8000;    proxy_pass $u; }
        location /incidents     { set $u http://incident_management:8000; proxy_pass $u; }
        location /audit         { set $u http://audit:8000;               proxy_pass $u; }
        location /notifications { set $u http://notification:8000;        proxy_pass $u; }
        # location /reports     { proxy_pass http://reporting:8000; }
        location /ingestion     { set $u http://ingestion:8020;           proxy_pass $u; }

        location /uc3           { set $u http://uc3_stub:8023;            proxy_pass $u; }

        location / { return 200 "Innovision gateway running"; }
    }
}
